# Generated by Django 3.1.5 on 2021-03-06 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import webpages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('property_description', models.TextField(blank=True, null=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(default='', max_length=128)),
                ('county', models.CharField(default='', max_length=128)),
                ('floor_plan', models.ImageField(blank=True, null=True, upload_to=webpages.models.get_image_filename)),
                ('property_type', models.IntegerField(choices=[[1, 'Detached House'], [2, 'Semi-detached House'], [4, 'Terraced House'], [3, 'Duplex']])),
                ('number_of_bedrooms', models.PositiveIntegerField()),
                ('number_of_bathrooms', models.PositiveIntegerField()),
                ('energy_rating', models.IntegerField(choices=[(15, 'A1'), (14, 'A2'), (13, 'A3'), (12, 'B1'), (11, 'B2'), (10, 'B3'), (9, 'C1'), (8, 'C2'), (7, 'C3'), (6, 'D1'), (5, 'D2'), (4, 'E1'), (3, 'E2'), (2, 'F'), (1, 'G')])),
                ('size', models.IntegerField()),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=webpages.models.get_image_filename, verbose_name='images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='webpages.post')),
            ],
        ),
    ]
