# Generated by Django 3.1.5 on 2021-03-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
