# Generated by Django 3.1.5 on 2021-03-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='post',
            name='address_line_1',
            field=models.CharField(max_length=255, verbose_name='Street address'),
        ),
        migrations.AlterField(
            model_name='post',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='District or Townland'),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(default='', max_length=128, verbose_name='City or town'),
        ),
        migrations.AlterField(
            model_name='post',
            name='county',
            field=models.CharField(choices=[('Antrim', 'Antrim'), ('Armagh', 'Armagh'), ('Carlow', 'Carlow'), ('Cavan', 'Cavan'), ('Clare', 'Clare'), ('Cork', 'Cork'), ('Donegal', 'Donegal'), ('Down', 'Down'), ('Dublin', 'Dublin'), ('Fermanagh', 'Fermanagh'), ('Galway', 'Galway'), ('Kerry', 'Kerry'), ('Kildare', 'Kildare'), ('Kilkenny', 'Kilkenny'), ('Laois', 'Laois'), ('Leitrim', 'Leitrim'), ('Limerick', 'Limerick'), ('Londonderry', 'Londonderry'), ('Longford', 'Longford'), ('Louth', 'Louth'), ('Mayo', 'Mayo'), ('Meath', 'Meath'), ('Monaghan', 'Monaghan'), ('Offaly', 'Offaly'), ('Roscommon', 'Roscommon'), ('Sligo', 'Sligo'), ('Tipperary', 'Tipperary'), ('Tyrone', 'Tyrone'), ('Waterford', 'Waterford'), ('Westmeath', 'Westmeath'), ('Wexford', 'Wexford'), ('Wicklow', 'Wicklow')], default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price (&euro;)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='property_type',
            field=models.CharField(choices=[('Detached House', 'Detached House'), ('Semi-detached House', 'Semi-detached House'), ('Terraced House', 'Terraced House'), ('Duplex', 'Duplex')], default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.PositiveIntegerField(verbose_name='Size (m<sup>2</sup>)'),
        ),
    ]
