# Generated by Django 3.1.5 on 2021-02-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_auto_20210212_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
