# Generated by Django 3.1.5 on 2021-02-17 22:55

from django.db import migrations, models
import django.db.models.deletion
import webpages.models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_auto_20210212_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=webpages.models.get_image_filename, verbose_name='images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_images', to='webpages.post')),
            ],
        ),
    ]
