# Generated by Django 3.1.5 on 2021-02-25 15:53

from django.db import migrations, models
import webpages.models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_auto_20210223_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='energy_rating',
            field=models.CharField(blank=True, choices=[('Exempted', 'Exempted'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('D1', 'D1'), ('D2', 'D2'), ('E1', 'E1'), ('E2', 'E2'), ('F', 'F'), ('G', 'G')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to=webpages.models.get_image_filename),
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_bathrooms',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_bedrooms',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Detached House', 'Detached House'), ('Semi-detached House', 'Semi-detached House'), ('Terraced House', 'Terraced House'), ('End of Terrace House', 'End of Terrace House'), ('Townhouse', 'Townhouse'), ('Apartment', 'Apartment'), ('Studio Apartment', 'Studio Apartment'), ('Duplex', 'Duplex'), ('Bangalow', 'Bangalow')], default='House', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='address_line_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='property_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
