# Generated by Django 3.1.5 on 2021-02-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=256)),
                ('property_area', models.IntegerField()),
                ('property_index', models.IntegerField()),
                ('property_index2', models.IntegerField()),
                ('property_index3', models.IntegerField()),
                ('property_index4', models.IntegerField()),
            ],
        ),
    ]
